version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    container_name: "mysql57"
    environment:
      MYSQL_ROOT_PASSWORD: somepass
      TZ: 'Asia/Shanghai'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
