version: '2'
services:
  redis:
    image: redis:5.0.0
    container_name: redis5
    command: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
